version: "3.7"

services:
  postgres_bd:
    image: postgres
    container_name: ddd-fullcycle
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ddd-fullcycle
    volumes:
      - .:/data/postgres
  app:
    build: .
    container_name: node
    restart: always
    volumes:
      - .:/usr/app
    depends_on:
      - postgres_bd
